const Images = {
	btn: {
		kakao_login_medium_wide: require('./btn/kakao_login_medium_wide.png'),

		outOrange: require('./btn/outOrange.png'),
		what: require('./btn/what.png'),

		backWhite: require('./btn/3x/backWhite.png'),
		chattingTabActive: require('./btn/3x/chattingTabActive.png'),
		chattingTabInactive: require('./btn/3x/chattingTabInactive.png'),
		closeModal: require('./btn/3x/closeModal.png'),
		closePage: require('./btn/3x/closePage.png'),
		deleteTextRed: require('./btn/3x/deleteTextRed.png'),
		deleteTextBrown: require('./btn/3x/deleteTextBrown.png'),
		editRed: require('./btn/3x/editRed.png'),
		editWhite: require('./btn/3x/editWhite.png'),
		exitRoom: require('./btn/3x/exitRoom.png'),
		homeTabActive: require('./btn/3x/homeTabActive.png'),
		homeTabInactive: require('./btn/3x/homeTabInactive.png'),
		menu: require('./btn/3x/menu.png'),
		plusChat: require('./btn/3x/plusChat.png'),
		profileTabActive: require('./btn/3x/profileTabActive.png'),
		profileTabInactive: require('./btn/3x/profileTabInactive.png'),
		searchRed: require('./btn/3x/searchRed.png'),
		selected: require('./btn/3x/selected.png'),
		sendChat: require('./btn/3x/sendChat.png'),
		settingTabActive: require('./btn/3x/settingTabActive.png'),
		settingTabInactive: require('./btn/3x/settingTabInactive.png'),
		unSelected: require('./btn/3x/unSelected.png'),
		heart: require('./btn/3x/heart.png'),
		plus: require('./btn/3x/plus.png'),
		deleteMissionWhite: require('./btn/3x/deleteMissionWhite.png'),
	},
	img: {
		A: require('./img/A.png'),
		arrowRight: require('./img/arrowRight.png'),
		B: require('./img/B.png'),
		profileSmall: require('./img/profileSmall.png'),
		mission: require('./img/mission.png'),

		arrowBoth: require('./img/3x/arrowBoth.png'),
		profileGame: require('./img/3x/profileGame.png'),
		dotFill: require('./img/3x/dotFill.png'),
		dotUnFill: require('./img/3x/dotUnFill.png'),
		triangle: require('./img/3x/triangle.png'),
		crown: require('./img/3x/crown.png'),
		lock: require('./img/3x/lock.png'),
		freeChat: require('./img/3x/freeChat.png'),
		manitoChat: require('./img/3x/manitoChat.png'),
		profileBig: require('./img/3x/profileBig.png'),
		loading: require('./img/3x/loading.gif'),
		master: require('./img/3x/master.png'),
		user: require('./img/3x/user.png'),
	},
	logo: {
		appLogo: require('./logo/appLogo.png'),
		appLogoBig: require('./logo/appLogoBig.png'),
		appLogoText: require('./logo/appLogoText.png'),
		manitoRed: require('./logo/manitoRed.png'),
		manitoWhite: require('./logo/manitoWhite.png'),
		maniteeRed: require('./logo/maniteeRed.png'),
		masterRed: require('./logo/masterRed.png'),
		makersRed: require('./logo/makersRed.png'),
		masterWhite: require('./logo/masterWhite.png'),
		mynameRed: require('./logo/mynameRed.png'),
		mynameWhite: require('./logo/mynameWhite.png'),
	},
};

export default Images;
